# Generated by Django 5.2.7 on 2025-10-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
